const teams = {
  team1: {
    name: "MURDER 3YES",
    title: "You better watch out!",
    description: "We have seen some things",
    video: "https://storage.opensea.io/files/073567afef981d31602c4756de193330.mp4",
    color: "#d9e46b",
    links: [
      { text: "Sisto", url: "https://twitter.com/NFT_MurderA"},
      { text: "NiftyCat", url: "https://twitter.com/Nifty_Cats"},
      { text: "J-838", url: "https://twitter.com/Jae838"},
      { text: "NFTUpdate", url: "https://twitter.com/NFTupdate"},
    ],
    votes: 1,
  },
  team2: {
    name: "PURPLE NURPLES",
    title: "Don't get it twisted!",
    description: "Wait until you see my master balls!",
    video: "https://storage.opensea.io/files/7923729ef08dde103a2a871211cfe3b7.mp4",
    color: "#af50ee",
    links: [
      { text: "HashBastards", url: "https://twitter.com/HashBastardsNFT"},
      { text: "Robbies", url: "https://twitter.com/robbiesnft"},
      { text: "HOLLYWEIRDZ", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "Junshi", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 1,
  },  
  team3: {
    name: "THE HALLOWS",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Momo", url: "https://twitter.com/MomoUhOh"},
      { text: "Searcher", url: "https://twitter.com/SearcherSunset"},
      { text: "IndigeTal", url: "https://twitter.com/IndigetalG"},
      { text: "Robbnotbob", url: "https://twitter.com/Robbnotbob1"},
    ],
    votes: 63,
  },
  team4: {
    name: "THE PROPHETS",
    title: "Our prediction is your defeat",
    description: "The crystal poke ball reveals all, so give up now or you’re bound to fall.",
    color: "#34c92a",
    video: "https://storage.opensea.io/files/94e382bc35a934fe72506f3cdd5f23fb.mp4",
    links: [
      { text: "Noisy", url: "https://twitter.com/noisynfts"},
      { text: "Crucifore", url: "https://twitter.com/crucifore"},
      { text: "Kingbob", url: "https://twitter.com/thehordekingbob"},
      { text: "Dweaver", url: "https://twitter.com/DWeaver803"},
    ],
    votes: 1, 
  },
  team5: {
    name: "CGSA",
    title: "Unknown",
    description: "Unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Quick Bill", url: "https://twitter.com/pxlhns"},
      { text: "Stray Alien", url: "https://twitter.com/zazanft"},
      { text: "Aya", url: "https://twitter.com/steamed_bunny"},
      { text: "Radio Pill", url: "https://twitter.com/sincosnft"},
    ],
    votes: 63,
  },
  team6: {
    name: "DIABLO",
    title: "Turning up the heat!",
    description: "If you step to us, you might get burned.",
    video: "https://storage.opensea.io/files/f5be73b750109ba9dffc790ad6d15026.mp4",
    color: "#18b3eb",
    links: [
      { text: "Valyrian", url: "https://twitter.com/LillsLou"},
      { text: "BRYMIC", url: "https://twitter.com/brymic_"},
      { text: "SoulzBruh", url: "https://twitter.com/SoulzBruh"},
      { text: "Calabasas", url: "https://twitter.com/CalabasasKidNFT"},
    ],
    votes: 1,
  },
  team7: {
    name: "X PuSsYxxMoNeYxxW33D X",
    title: "You don't want this fight!",
    description: "You won't stand a chance against us!",
    video: "https://storage.opensea.io/files/38945227803851764ca9482dda239a3a.mp4",
    color: "#ff3af6",
    links: [
      { text: "Stacy", url: "https://twitter.com/cryptostacys"},
      { text: "Socra", url: "https://twitter.com/SocratreesMusic"},
      { text: "Devil", url: "https://twitter.com/"},
      { text: "NONE", url: "https://twitter.com/NONE32X32"},
    ],
    votes: 1,
  },
  team8: {
    name: "Poké-Morghulis",
    title: "You better be scared of us!",
    description: "We got this in the bag. Nobody can come close!",
    video: "https://storage.opensea.io/files/1f60aa2933117a421f8985265de4ab93.mp4",
    color: "#296fdb",
    links: [
      { text: "Anze", url: "https://twitter.com/HashBastardsNFT"},
      { text: "Super Blitz", url: "https://twitter.com/robbiesnft"},
      { text: "LolTapes", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "Rudy", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 1,
  },
  team9: {
    name: "TEAM NAKED",
    title: "The naked menace!",
    description: "We will be the best, like no one ever was! Because nakedness is justice.",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#eb8ada",
    links: [
      { text: "Zaza", url: "https://twitter.com/ZazaNFT"},
      { text: "Sincos", url: "https://twitter.com/sincosNFT"},
      { text: "Hans", url: "https://twitter.com/pxlhns"},
      { text: "Steamed Bun", url: "https://twitter.com/Steamed_Bunny"},
    ],
    votes: 1,
  },
  team10: {
    name: "LASER EYES",
    title: "Lasers set to lethal!",
    description: "We know your every move!",
    video: "https://storage.opensea.io/files/711a90737f893034650926df22a1dcea.mp4",
    color: "#8813eb",
    links: [
      { text: "Big Rob", url: "https://twitter.com/bigrobatx"},
      { text: "PugBits", url: "https://twitter.com/PugBits"},
      { text: "Content Beware", url: "https://twitter.com/Contentbeware"},
      { text: "dis0ri3nted", url: "https://twitter.com/dis0ri3nted"},
    ],
    votes: 1,
  },
  team11: {
    name: "FIRE FAIRYS",
    title: "Fight fire with fire!",
    description: "We are too hot to handle!",
    video: "https://storage.opensea.io/files/3df711c3c2b4d19e33f8aa19033f0ba5.mp4",
    color: "#e95f5f",
    links: [
      { text: "rentfx", url: "https://twitter.com/renftx"},
      { text: "Bones", url: "https://twitter.com/BonesClub_NFT"},
      { text: "dpop", url: "https://twitter.com/deepopped"},
      { text: "Gersch", url: "https://twitter.com/thedavidgersch"},
    ],
    votes: 63,
  },
  team12: {
    name: "FLUFFY TOUGH BOYZ",
    title: "Get Tough, Get Fluffed!",
    description: "Fists of furry win in a hurry",
    video: "https://storage.opensea.io/files/b47ff716a6d0f1ef0d4e542b43e3c1de.mp4",
    color: "#c52696",
    links: [
      { text: "Bored Blind Devil", url: "https://twitter.com/BoredBlindDevil"},
      { text: "Gutter Trevor", url: "https://twitter.com/Trevor4ever210"},
      { text: "Trevor", url: "https://twitter.com/Trevor4ever210"},
      { text: "2ULUX5", url: "https://twitter.com/2ulux5"},
    ],
    votes: 1,
  },
  team13: {
    name: "TEAM ROCKET TO THE MOON",
    title: "Prepare for brutal trouble!",
    description: `Make it quadrupal, not double!\nTo Protect NFTs from devastation,\nUniting all peoples, beyond the nations.\nTo denouce all evil, find peace and love,\nTo extend our reach to the Moon above!`,
    video: "https://storage.opensea.io/files/51ea8d414210fd00c83518084d0b39f9.mp4",
    color: "#f1a026",
    links: [
      { text: "Digi", url: "https://twitter.com/ItsDigi_NFT"},
      { text: "PixelKnights", url: "https://twitter.com/PixelKnightsNFT"},
      { text: "Reapers", url: "https://twitter.com/crypto_reapers"},
      { text: "Maslo", url: "https://twitter.com/NFT_MASLO"},
    ],
    votes: 1,
  },
}




// const teamNaked = {
//   name: "Team Naked",
//   title: "The naked menace!",
//   description: "We will be the best, like no one ever was! <br> Because nakedness is justice!",
//   video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
//   color: "#ff00a0",
//   links: [
//     { text: "Pixelhans", url: "https://twitter.com/pxlhns"},
//     { text: "Zaza", url: "https://twitter.com/zazanft"},
//     { text: "Steamed Bun", url: "https://twitter.com/steamed_bunny"},
//     { text: "Sincos", url: "https://twitter.com/sincosnft"},
//   ],
//   votes: 63,
// }

// const teamPurpleNurple = {
//   name: "Purple Nurple",
//     title: "Undefeated in combat",
//     description: "You stand no chance! For we have the power of purp nurps! \n We will prevail ahahahaha",
//     color: "#c787f8",
//     video: "https://storage.opensea.io/files/7923729ef08dde103a2a871211cfe3b7.mp4",
//     links: [
//       { text: "HashBastards", url: "https://twitter.com/"},
//       { text: "HOLLYWEIRDZ", url: "https://twitter.com/"},
//       { text: "Junshi", url: "https://twitter.com/"},
//       { text: "Robbies", url: "https://twitter.com/"},
//     ],
//     votes: 63,
// }

// const teamProphet = {
//   name: "The Prophets",
//   title: "Our prediction is your defeat",
//   description: "The crystal poke ball reveals all, so give up now or you’re bound to fall.",
//   color: "#34c92a",
//   video: "https://storage.opensea.io/files/94e382bc35a934fe72506f3cdd5f23fb.mp4",
//   links: [
//     { text: "Noisy", url: "https://twitter.com/noisynfts"},
//     { text: "Kingbob", url: "https://twitter.com/thehordekingbob"},
//     { text: "DannyBlaze", url: "https://twitter.com/"},
//     { text: "Crucifore", url: "https://twitter.com/crucifore"},
//   ],
//   votes: 63, 
// }
