const teams = {
  team1: {
    name: "MURDER 3YES",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Sisto", url: "https://twitter.com/NFT_MurderA"},
      { text: "NiftyCat", url: "https://twitter.com/Nifty_Cats"},
      { text: "J-838", url: "https://twitter.com/Jae838"},
      { text: "NFTUpdate", url: "https://twitter.com/NFTupdate"},
    ],
    votes: 63,
  },
  team2: {
    name: "PURPLE NURPLES",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "HashBastards", url: "https://twitter.com/HashBastardsNFT"},
      { text: "Robbies", url: "https://twitter.com/robbiesnft"},
      { text: "HOLLYWEIRDZ", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "Junshi", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 63,
  },  
  team3: {
    name: "THE HALLOWS",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Momo", url: "https://twitter.com/MomoUhOh"},
      { text: "Searcher", url: "https://twitter.com/SearcherSunset"},
      { text: "IndigeTal", url: "https://twitter.com/IndigetalG"},
      { text: "Robbnotbob", url: "https://twitter.com/Robbnotbob1"},
    ],
    votes: 63,
  },
  team4: {
    name: "THE PROPHETS",
    title: "Our prediction is your defeat",
    description: "The crystal poke ball reveals all, so give up now or you’re bound to fall.",
    color: "#34c92a",
    video: "https://storage.opensea.io/files/94e382bc35a934fe72506f3cdd5f23fb.mp4",
    links: [
      { text: "Noisy", url: "https://twitter.com/noisynfts"},
      { text: "Crucifore", url: "https://twitter.com/crucifore"},
      { text: "Kingbob", url: "https://twitter.com/thehordekingbob"},
      { text: "Dweaver", url: "https://twitter.com/DWeaver803"},
    ],
    votes: 140, 
  },
  team5: {
    name: "CGSA",
    title: "Unknown",
    description: "Unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Quick Bill", url: "https://twitter.com/pxlhns"},
      { text: "Stray Alien", url: "https://twitter.com/zazanft"},
      { text: "Aya", url: "https://twitter.com/steamed_bunny"},
      { text: "Radio Pill", url: "https://twitter.com/sincosnft"},
    ],
    votes: 63,
  },
  team6: {
    name: "DIABLO",
    title: "Turning up the heat!",
    description: "If you step to us, you might get burned.",
    video: "https://storage.opensea.io/files/f5be73b750109ba9dffc790ad6d15026.mp4",
    color: "#18b3eb",
    links: [
      { text: "Valyrian", url: "https://twitter.com/LillsLou"},
      { text: "BRYMIC", url: "https://twitter.com/brymic_"},
      { text: "SoulzBruh", url: "https://twitter.com/SoulzBruh"},
      { text: "Calabasas", url: "https://twitter.com/CalabasasKidNFT"},
    ],
    votes: 1,
  },
  team7: {
    name: "X PuSsYxxMoNeYxxW33D X",
    title: "You don't want this fight!",
    description: "You won't stand a chance against us!",
    video: "https://storage.opensea.io/files/38945227803851764ca9482dda239a3a.mp4",
    color: "#ff3af6",
    links: [
      { text: "Stacy", url: "https://twitter.com/cryptostacys"},
      { text: "Socra", url: "https://twitter.com/SocratreesMusic"},
      { text: "Devil", url: "https://twitter.com/"},
      { text: "NONE", url: "https://twitter.com/NONE32X32"},
    ],
    votes: 1,
  },
  team8: {
    name: "Poké-Morghulis",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Anze", url: "https://twitter.com/HashBastardsNFT"},
      { text: "Super Blitz", url: "https://twitter.com/robbiesnft"},
      { text: "LolTapes", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "Rudy", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 63,
  },
  team9: {
    name: "TEAM NAKED",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Zaza", url: "https://twitter.com/HashBastardsNFT"},
      { text: "Sincos", url: "https://twitter.com/robbiesnft"},
      { text: "Hans", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "Steamed Bun", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 63,
  },
  team10: {
    name: "LASER EYES",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Big Rob", url: "https://twitter.com/HashBastardsNFT"},
      { text: "PugBits", url: "https://twitter.com/robbiesnft"},
      { text: "Content Beware", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "dis0ri3nted", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 63,
  },
  team11: {
    name: "FIRE FAIRYS",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "rentfx", url: "https://twitter.com/HashBastardsNFT"},
      { text: "Bones", url: "https://twitter.com/robbiesnft"},
      { text: "dpop", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "Gersch", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 63,
  },
  team12: {
    name: "FLUFFY TOUGH BOYZ",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Bored Blind Devil", url: "https://twitter.com/HashBastardsNFT"},
      { text: "Gutter Trevor", url: "https://twitter.com/robbiesnft"},
      { text: "Trevor", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "2ULUX5", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 63,
  },
  team13: {
    name: "TEAM ROCKET TO THE MOON",
    title: "unknown!",
    description: "unknown",
    video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
    color: "#ff00a0",
    links: [
      { text: "Digi", url: "https://twitter.com/HashBastardsNFT"},
      { text: "PixelKnights", url: "https://twitter.com/robbiesnft"},
      { text: "Reapers", url: "https://twitter.com/HOLLYWEIRDZ420"},
      { text: "Maslo", url: "https://twitter.com/JunshiNFT"},
    ],
    votes: 63,
  },
}




// const teamNaked = {
//   name: "Team Naked",
//   title: "The naked menace!",
//   description: "We will be the best, like no one ever was! <br> Because nakedness is justice!",
//   video: "https://storage.opensea.io/files/24266851c4c0e67ff0813062a7424a5d.mp4",
//   color: "#ff00a0",
//   links: [
//     { text: "Pixelhans", url: "https://twitter.com/pxlhns"},
//     { text: "Zaza", url: "https://twitter.com/zazanft"},
//     { text: "Steamed Bun", url: "https://twitter.com/steamed_bunny"},
//     { text: "Sincos", url: "https://twitter.com/sincosnft"},
//   ],
//   votes: 63,
// }

// const teamPurpleNurple = {
//   name: "Purple Nurple",
//     title: "Undefeated in combat",
//     description: "You stand no chance! For we have the power of purp nurps! \n We will prevail ahahahaha",
//     color: "#c787f8",
//     video: "https://storage.opensea.io/files/7923729ef08dde103a2a871211cfe3b7.mp4",
//     links: [
//       { text: "HashBastards", url: "https://twitter.com/"},
//       { text: "HOLLYWEIRDZ", url: "https://twitter.com/"},
//       { text: "Junshi", url: "https://twitter.com/"},
//       { text: "Robbies", url: "https://twitter.com/"},
//     ],
//     votes: 63,
// }

// const teamProphet = {
//   name: "The Prophets",
//   title: "Our prediction is your defeat",
//   description: "The crystal poke ball reveals all, so give up now or you’re bound to fall.",
//   color: "#34c92a",
//   video: "https://storage.opensea.io/files/94e382bc35a934fe72506f3cdd5f23fb.mp4",
//   links: [
//     { text: "Noisy", url: "https://twitter.com/noisynfts"},
//     { text: "Kingbob", url: "https://twitter.com/thehordekingbob"},
//     { text: "DannyBlaze", url: "https://twitter.com/"},
//     { text: "Crucifore", url: "https://twitter.com/crucifore"},
//   ],
//   votes: 63, 
// }
